// frases.js
const frasesCulturaPop = [
    "¡Hasta la vista, baby! - Terminator 2",
    "Que la Fuerza te acompañe. - Star Wars",
    "Volveré. - Terminator",
    "Luke, yo soy tu padre. - Star Wars",
    "Houston, tenemos un problema. - Apollo 13",
    "Sayonara, baby. - Terminator 2",
    "No siento las piernas. - Rambo",
    "¡Es una trampa! - Star Wars",
    "Mi tesoro. - El Señor de los Anillos",
    "Elija la pastilla roja. - Matrix",
    "Yo soy tu padre. - Star Wars",
    "Tienes que ver para creer. - Matrix",
    "No hay lugar como el hogar. - El Mago de Oz",
    "Elemental, mi querido Watson. - Sherlock Holmes",
    "Estoy en una misión de Dios. - Los Hermanos Caradura",
    "Sólo hay una cosa que odio más que los muggles: las tareas de la escuela. - Harry Potter",
    "Saludad a mi pequeño amigo. - Scarface",
    "Houston, tenemos un problema. - Apollo 13",
    "La vida es como una caja de bombones. - Forrest Gump",
    "Hakuna Matata. - El Rey León",
    "Que el viento siempre esté a tu favor. - Los Juegos del Hambre",
    "Me encanta el olor del napalm por la mañana. - Apocalypse Now",
    "No hay lugar como el hogar. - El Mago de Oz",
    "Que el viento siempre esté a tu favor. - Los Juegos del Hambre",
    "Estoy volando, Jack. - Titanic",
    "Elija la pastilla roja. - Matrix",
    "La avaricia es buena. - Wall Street",
    "Hasta el infinito y más allá. - Toy Story",
    "Aquí tienes a Johnny. - El Resplandor",
    "Mi tesoro. - El Señor de los Anillos",
    "No hay lugar como el hogar. - El Mago de Oz",
    "¿Me estás hablando a mí? - Taxi Driver",
    "Voy a hacerle una oferta que no podrá rechazar. - El Padrino",
    "Sólo hay una cosa que odio más que los muggles: las tareas de la escuela. - Harry Potter",
    "¡Hasta la vista, baby! - Terminator 2",
    "Volveré. - Terminator",
    "Que la Fuerza te acompañe. - Star Wars",
    "Yo soy Groot. - Guardianes de la Galaxia",
    "Te necesito. - Harry Potter",
    "Nunca digas adiós. - La Novia Cadáver",
    "Sólo hay una cosa que odio más que los muggles: las tareas de la escuela. - Harry Potter",
    "Saludad a mi pequeño amigo. - Scarface",
    "¡Es una trampa! - Star Wars",
    "La vida es como una caja de bombones. - Forrest Gump",
    "Hakuna Matata. - El Rey León",
    "Me encanta el olor del napalm por la mañana. - Apocalypse Now",
    "Hasta el infinito y más allá. - Toy Story",
    "Aquí tienes a Johnny. - El Resplandor",
    "Voy a hacerle una oferta que no podrá rechazar. - El Padrino"
];